* Both fiction and non-fiction books have a place in our lives
:PROPERTIES:
:Date: 2021-04-03
:tags: literature
:END:

** Note
I've been thinking about the topic of reading fiction vs non-fiction. And by non-fiction, I mean mainly the
self-improvement books that have taken the world by storm lately. Or any book that tries to teach you something
about life in general. There's been a lot of people that have started to read only non-fiction books and while
that is not bad in itself, as it's a choice that everyone makes based on their interests and desires, some of
these individuals have started to bash fiction as "nonsensic, unrealistic and ultimately
pointless". Paraphrasing, of course. But the general sentiment is there. Non-fiction is "better" because it
teaches you about life, about the real world and how to live a better life, how to navigate the labyrinth that
is our everyday existence. And it's the only type of book worth our time.

Now this borders on the understanding that our every waking moment must as productive as possible, as we have so
little time that we can't afford to do otherwise, lest we miss out on so much! There's an often seen tendency
lurking behind statements like this - the fear of missing out (or FOMO as the cool kids call it). It's the idea
that there is so much happening in the world at all times and that if you're not acting and learning and doing
something every single second of the day, you will miss out on what could potentially be something groundbreaking
and lifechanging, and then you would berate yourself endlessly for doing so. It's become an obsession for some
people.

I can fully understand the viewpoint here, as I often struggle with this as well. I constantly think, as a
programmer, that by not learning or trying out a new technology, I'm missing out on what potentially could be
the best thing I've ever seen and it'll change my professional career forever. So, bottom line, the
understanding it to read as many non-fiction books as possible, so you can learn as much as possible, because
these are the books that are worth your time, they teach you valuable and priceless life skills that you can't
live without.

That all sounds fine and dandy, but there's an issue. We can't always be productive and at full capacity. Our
body needs to power down and recharge, and we often ignore it because of these exact reasons - push forward, as
there's no time. Well, we have to accept the fact that we need rest in order to actually be productive. And
that's where, for me, fiction comes, and to me it's learning in the same way I can learn from non-fiction books,
but not with the same level of perceived deep focus and desire to consume the content and project it on my own
life.

Now, I'm not saying non-fiction books are useless. No, they all have a place in life. I'm arguing that
fiction books have a lot of benefits as well in terms of learning, developing your imagination, winding down,
and, in essence, escaping a bit from everyday reality. Because I don't know about you, but after a long day at
work and of being in the real world, I enjoy distancing myself from it, going into an entirely different one, or
at least into an entirely different mindset that's not necessarily focused on the problems the everyday person
faces.

Fiction books are of the imaginary as well as the unusual. They can put you into worlds that do not exist, but
that are created by the human imagination. They are shaped in new, exciting ways, with novel ways to look at
things. I can weigh the moral decisions of characters who make them in circumstances so unlike my own that I can
see the real intent behind them, without biasing them with my own experience. Picturing it all in my head helps
me be more creative, because I don't put limits on my imagination, and more often than not, I can discover that
real life is not limited to what we see either. It might not be real, but what's in your head is only yours, and
often a way to deal with stuff happening in your life is to put in a fresh perspective and really weigh it
according to your own system of beliefs.

Whether it's a fantasy world with dragons and elves, or a distant science fiction future, or a modern day book
following the story of someone just like you, in the end, it's all written by a human, it's all simply a
different viewpoint. A perspective that's presented in an entirely new way. And it feels fresh, it feels
relaxing, and it takes the pressure off better than any book on mindfulness can, at least for me. It's my own
little thicket of imagination that I can do whatever I want with. And it's not someone telling me to do this or
to do that to be successful, it's me creating a place for myself where I can simply be whatever I want to
be. And that's in no way missing out, because it actually helps me to be a more mindful and focused person in
the present, because i've let my brain wonder freely and get the rest it deserves.
** Links
[[z:/daily_journaling_resource?type=branch]]
