* Braindumping as a writing, thinking and relaxing exercise
:PROPERTIES:
:Date: 2021-04-03
:tags: literature
:END:

** Note
Braindumping is something i've been doing for a while and it's become a big part of my morning routine (or
evening routine at times as well). And while it's not a type of writing that always produces content that is
pure gold or that can be instantly used in notes or in books, I believe it's just as powerful. Here's a couple
of the main benefits for me.

It clears out your brain. Our brains are usually full of all kinds of thoughts, good or bad (mostly bad, as
that's the unfortunate way our mind works) and it can be overwhelming to wake up to that. Most of these thoughts
are fleeting, they don't have real sustenance, nor are they complete enough for us to really focus on them.

So, what can we do? That's right, we can dump them. We take a piece of paper, physical or digital, and we just
write down what we're thinking. All of it. No censure. As it's something personal, something that no one will
see unless you want them to. Encrypt it if you wish (I do so) to have that extra layer of certainty. And when
you write them down, these nagging thoughts that are filling up your head with garbage and aren't letting you
think straight, because apparently while you were sleeping your brain was playing a game of "let's figure out
the worst possible scenarios in life", you'll feel free. Free to focus on more important, real and tangible
things. Because you've taken out the trash.

And who knows, something good might even result from these scribblings. I know they have for me. Some sensible
ideas have been written down in these moments. This note is one of those things.

It makes your writing better. Writing is a skill and has to be practiced as all others. If you have the daily
practice of braindumping or journaling, you'll be practicing writing free form words on paper, without too much
critique or strain to make it perfect, as you're writing this for yourself. It doesn't have to be Shakespeare
material. Growing things out of an unfinished state and polishing them is the whole concept of the digital
garden that i'm very intrigued by, but that's another topic. To stay on top of a skill and to be able to write
when you're being paid for it or when you're doing serious writing is no small thing. It gives you
confidence. Because, after all, you're already doing it every day, it'll be no more special or different than
your morning/evening practice.

It lets you develop insights about your own thoughts. You'd be surprised what can come out of you when you just
let your thoughts flow. Garbage, surely, but also things that you never consciously noticed you're thinking,
that have been bubbling under the surface. Writing this way is a conversation with yourself, a way to delve into
your mind and discover what's going on inside that vortex of seemingly random thoughts. Connections can pop-up,
ideas, ambitions, and more. It's a journey of self-discovery. Of course, that doesn't always happen, but more
often that not i'm impressed by what i'm reading. Who knew? Those thoughts usually get extracted somewhere else
for reuse. As I mentioned in the beginning, that is a nice byproduct of your braindumping, but taking off the
pressure of writing something like that on purpose is very freeing. It helps you be more confident in your own
self and mind, and that will project on every other part of your life.

So, take a journal, and start your day off with a braindump. Who knows what you might discover? If nothing else,
it's a pleasant experience. And brings the benefit of a bit more mental clarity. And who doesn't want that,
especially in this crazy world we now live in?
** Links
[[z:/daily_journaling_resource?type=branch]]
