* Five minute journal and idea journal
:PROPERTIES:
:Date: 2021-03-25T22:21
:tags: literature
:END:

** Note
*** Five minute journal
The five minute journal is a way to increase focus and help you appreciate the little things.
It revolves around writing the following things every(-ish) day:

In the morning:

1. What i'm grateful for (x3)
2. What I can do to make today good (x3)
3. Daily affirmations, things like "i'm something, i'm something else". Sounds quite reassuring. (x2)

In the evening:

1. Amazing things that happened today (might have to be a bit creative, not the biggest fan of the word amazing) (x3)
2. How could I have made today better? ( I like this one ) (x2)

*** Idea journal
The author gave some pretty interesting ones ( like cut off is legs ). But this one is quite obvious - have a small journal for when the inspiration strikes for ideas and goals that you think of during the day. These should be reviewed - a week after, a quarter after, and underline what sounds interesting. Sounds like a good way to pinpoint my often appearing ideas for projects.
** Links
[[z:/journaling_and_note_taking_by_tim_ferriss?type=branch]]
