* Permanent notes in a Zettelkasten
:PROPERTIES:
:Date: 2021-03-18T22:51
:tags: literature
:END:

** Note
A permanent note, or a zettel, is the main building block of a zettelkasten. It's a single, atomic,
self-sufficient idea that connects to other, already existing ideas in the slip box. A permanent note can also
be added to at any time as new information surfaces, so it "grows" in a way. It's the main product of the note
taking process, and serves as a basis for writing afterwards.
Permanent notes most commonly appear as a joining of literature notes.

So, what to consider when making a permanent note out of ideas from a literature note - will I use this later in
writing or is this relevant to other already existing notes?

Tag notes by the context in which you wish to find them.

A good idea I had found is notes being sentences or parts of sentences, which you can then reference in other notes.

Permanent notes have:
- permanent note tag
- topic tags
- links to a literature note
- relevant other permanent notes and explanations why and how they are linked
- summary of the idea

** Links
[[z:/zettelkasten_fundamentals?type=branch]]
