* Self confidence is strongly tied to self worth
:PROPERTIES:
:Date: 2021-03-28
:tags: literature
:END:

** Note
Self confidence and self esteem are tied very strongly to your feeling of self worth. If you don't feel like
you're worthy of happiness, you cannot have confidence. And the opposite. If a child does not receive the love
and affection they deserve, they start to believe it's their fault, and that projects onto their adulthood which builds upon the feeling of unworthiness.

The worst thing is that people are so afraid of failure they do not even try. They don't even question being
"unhappy". They settle for toxic relationships. They are afraid to put themselves out there.

We naturally start to think that something outside of us will make you happy, that if we "have all this
stuff" it will make us happy.
Where does our low self confidence come from? This all comes from outside the vale of consciousness (subconscious).
If we've had a bad childhood, we think that by doing everything "right" in life - careerwise, familywise,
relationshipwise, that's how happiness will come. (Spoiler alert, it's not that, it's brainwashing by society and by
some external entity - parents, etc.)
Our limiting beliefs are not our own voice, it's a reflection of the outside experiences.
** Links
[[z:/boosting_your_self_confidence?type=branch]]
