* The mind can be our most valuable asset and our greatest enemy
:PROPERTIES:
:Date: 2021-03-21T18:18
:tags: literature
:END:

** Note
The mind is our most valuable asset. But it also can be our biggest enemy. It's ironic. If we learn to condition
it, to calm it, to control it to focus on the positive and the drive to improve ourselves, we can go a long way
to making our life better. Letting the bad thoughts float past us, because that's what they are - fleeting. We
have lived out so many terrible things in our heads that will never come to pass. And they are not helping in
any way. Only making us feel worse and sometimes, leading to terrible things. What a mind can do when it's
influenced by something like the internet! It's scary to think about. Mindfulness, meditation, constant care is
what the mind requires. You can let it flow, let the ideas come, but when a bad one appears on the horizon,
don't let it take root. Think about how it's helping you right now, the answer will probably be in no way is it
helping you. Then let it pass by focusing on the body, by focusing on something tangible, so that the bad
thought can go its way out of the mind. And therein lies the key to a healthy mind. Well, at least I hope so.
** Links
[[z:/daily_journaling_resource?type=branch]]
