* We might not need confidence to begin
:PROPERTIES:
:Date: 2021-03-21T18:18
:tags: literature
:END:

** Note
We might not need this thing called confidence. But rather we need to condition our minds, to help them
realize two things - life is short, and you don't have that much to lose that you can afford to attribute every
lack of action to lack of confidence. It's a vicious circle of sorts - you can't perform actions without
confidence, you can't get confidence without performing successful actions. So why don't we just eliminate the
middle man? Something I heard in Young Sheldon struck me as quite deep. What do I do when i'm afraid? He asks
his sister. She says: "I guess we should be afraid and do it anyway." And how true that rings! While someone is
thinking how little confidence they have and how they can't achieve anything because their confidence has been
defeated by life, someone else just takes the step. Despite being afraid and not having confidence. The mind can
always convince us that we can't do something. It's just what it does. It's a parasite of sorts. Annoys the hell
out of me. So, in the end, ask yourself not am I confident enough, but rather, what exactly do I have to lose?
Is it worth actually not doing it because of that? I'm fairly certain in most cases the answer will be no it's
not. Because you'll regret it. And regret is not something you want to die with. You regret the things you
didn't do more than those you do. What would've happened if I'd taken that opportunity to do something? That I
passed it up because I thought I wasn't confident enough. But looking back, it would've only helped me. And the
fear of failure and lack of confidence don't matter all that much anymore.


** Links
[[z:/daily_journaling_resource?type=branch]]
