* Finding what you love to do
:PROPERTIES:
:Date: 2021-04-26
:tags: stream
:END:

** Note
There's a special feeling you get when you're doing something you love. It's like nothing else, and it comes
naturally, not forced at all, and you know it inside. We don't always notice it, though. Whether it's everyday
life tasks that are occupying our time, or we're spending time searching for and reading what others tell us we
should do, we tend to strafe further and further away from what we love to do. Because we don't always notice
it, we take it for granted. And bow down to society's expectations of what's "profitable" and "successful". And
it's with the things we love that we can spend the most time, unnoticed, unregistered, just because you lose
track of time while doing them.

A mundane and boring task or job will have you looking at the clock every second of every day.

Something you love will make you forget there's a clock at all. To notice that, and embrace it, embracing
ourselves, that's where the beauty of it lies.
