* Gopass - a nice password manager
:PROPERTIES:
:Date: 2021-05-05
:tags: stream
:END:

** Note
The use case for a password manager should be obvious - we have lots of accounts with lots of passwords, and
it's not safe for all those passwords to be the same. ( though a lot of people do it, but that's their problem )
So how do we manage all these passwords and make forgetting them a thing of the past? We can use a password
manager.

There's lots of password managers that run in the browser or in desktop apps for example. Since i'm a fan of the
terminal world however, I naturally want to find a terminal password manager. There's =pass=, the ancient and
awesome GNU password manager. It works great, but there are some more modern versions of it that have appeared
recently. Basically =pass= with sugar on top.

One of those is [[https://www.gopass.pw/][gopass]]. I've been using it for a while and it's great. It can
integrate seamlessly with a git repository to store its data so it can be synced between multiple machines. It
uses a GPG key to encrypt everything, so your data is safe (as long as you can keep hold of your private gpg
key, of course).
Gopass stores the passwords in a password store on your local system.

Here's some of the basic features:

To add a new password

#+begin_src sh
gopass create
#+end_src

You'll get a handy wizard for creating a password, it can also generate a password for you.

To view all passwords
#+begin_src sh
gopass ls
#+end_src

It categorizes the entries nicely and provides autocompletion for them.

To copy a password to the clipboard (for a time)
#+begin_src sh
gopass show -c websites/login/password
#+end_src

To clone an existing password store from a git repo (when syncing on another machine for example).

You'll have to add the new machine as a recipient (e.g. add its public gpg key to the store so that it can read passwords)

#+begin_src sh
gopass clone repo_url
#+end_src

This and more can be found in this awesome gopass [[https://woile.github.io/gopass-cheat-sheet/][cheatsheet]].

Having a password manager has taken a big load off my mind - remembering passwords and constantly having to
reset them because I use different permutations of the same passwords for everything and can never remember
which i've used.
