name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  neuron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
    # You may pin to the exact commit or the version.
    # uses: cachix/install-nix-action@07da2520eebede906fbeefa9dd0a2b635323909d
      uses: cachix/install-nix-action@v1
    - name: Install neuron v1
      run: |
        nix-env -if https://github.com/srid/neuron/archive/v1.tar.gz
    - name: Build neuron site 🔧
      run: |
        ./neuron -d $PWD rib
    - name: Deploy to gh-pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .neuron/output/
